/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto.calculadora;

import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class calculadora20 extends javax.swing.JFrame {


    public calculadora20() {
        initComponents();
    }
    double numero1, numero2;
    String sinal;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        operator1 = new javax.swing.JLabel();
        operator2 = new javax.swing.JLabel();
        valor1 = new javax.swing.JTextField();
        valor2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        result = new javax.swing.JLabel();
        clearOperators = new javax.swing.JButton();
        divisor = new javax.swing.JButton();
        multiplicacao = new javax.swing.JButton();
        subtracao = new javax.swing.JButton();
        soma = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtTitulo = new javax.swing.JLabel();
        ButtonCE = new javax.swing.JButton();

        jLabel4.setText("jLabel4");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        operator1.setText("Operador 1 :");
        getContentPane().add(operator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 78, -1, -1));

        operator2.setText("Operador 2 :");
        getContentPane().add(operator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 105, -1, -1));

        valor1.setBackground(new java.awt.Color(0, 153, 204));
        valor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valor1ActionPerformed(evt);
            }
        });
        getContentPane().add(valor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 75, 148, -1));

        valor2.setBackground(new java.awt.Color(0, 153, 204));
        getContentPane().add(valor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 102, 148, -1));

        jLabel2.setText("Resultado");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 135, -1, -1));

        result.setText("0");
        getContentPane().add(result, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 135, 52, -1));

        clearOperators.setText("AC");
        clearOperators.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearOperatorsActionPerformed(evt);
            }
        });
        getContentPane().add(clearOperators, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 52, 36));

        divisor.setText("/");
        divisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisorActionPerformed(evt);
            }
        });
        getContentPane().add(divisor, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 52, 36));

        multiplicacao.setText("*");
        multiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicacaoActionPerformed(evt);
            }
        });
        getContentPane().add(multiplicacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 52, 36));

        subtracao.setText("-");
        subtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtracaoActionPerformed(evt);
            }
        });
        getContentPane().add(subtracao, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 52, 36));

        soma.setText("+");
        soma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                somaActionPerformed(evt);
            }
        });
        getContentPane().add(soma, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 52, 36));

        jButton16.setText("=");
        jButton16.setBorder(null);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 111, 38));

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));

        txtTitulo.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        txtTitulo.setText("Calculadora");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(txtTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(70, 70, 70))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txtTitulo)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 274, -1));

        ButtonCE.setText("CE");
        ButtonCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCEActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 52, 38));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void somaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_somaActionPerformed
    try{numero1 = Double.parseDouble(valor1.getText());
        numero2 = Double.parseDouble(valor2.getText());}
    catch(NumberFormatException ex){JOptionPane.showMessageDialog(null, "Só podem apenas números");}
        
        sinal = "soma";
        //valor1.setText("");
    }//GEN-LAST:event_somaActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        //numero2 = Double.parseDouble(valor1.getText());
        //valor1.setText("");
        double resultado;
        if(sinal == "soma"){
            result.setText(String.valueOf(numero1 + numero2));
            try{numero1 = Double.parseDouble(result.getText());}catch(NumberFormatException ex){JOptionPane.showMessageDialog(null,"Apenas numeros");}
        }
        if(sinal == "subtracao"){
            result.setText(String.valueOf(numero1 - numero2));
            try{numero1 = Double.parseDouble(result.getText());}catch(NumberFormatException ex){JOptionPane.showMessageDialog(null,"Apenas numeros");}
        }
        if(sinal == "multiplicacao"){
            result.setText(String.valueOf(numero1 * numero2));
            try{numero1 = Double.parseDouble(result.getText());}catch(NumberFormatException ex){JOptionPane.showMessageDialog(null,"Apenas numeros");}
        }
        if(sinal == "divisao"){
            result.setText(String.valueOf(numero1 / numero2));
            try{numero1 = Double.parseDouble(result.getText());}catch(NumberFormatException ex){JOptionPane.showMessageDialog(null,"Apenas numeros");}
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void subtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtracaoActionPerformed
        try{numero1 = Double.parseDouble(valor1.getText());
        numero2 = Double.parseDouble(valor2.getText());}catch(NumberFormatException ex){JOptionPane.showMessageDialog(null, "Só podem apenas números");}
        sinal = "subtracao";
    }//GEN-LAST:event_subtracaoActionPerformed

    private void multiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplicacaoActionPerformed
        try{numero1 = Double.parseDouble(valor1.getText());
        numero2 = Double.parseDouble(valor2.getText());}catch(NumberFormatException ex){JOptionPane.showMessageDialog(null, "Só podem apenas números");}
        sinal = "multiplicacao";
    }//GEN-LAST:event_multiplicacaoActionPerformed

    private void divisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisorActionPerformed
        try{numero1 = Double.parseDouble(valor1.getText());
        numero2 = Double.parseDouble(valor2.getText());}catch(NumberFormatException ex){JOptionPane.showMessageDialog(null, "Só podem apenas números");}
        sinal = "divisao";
    }//GEN-LAST:event_divisorActionPerformed

    private void clearOperatorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearOperatorsActionPerformed
        valor1.setText("");
        valor2.setText("");
        result.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_clearOperatorsActionPerformed

    private void valor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valor1ActionPerformed

    private void ButtonCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCEActionPerformed
    
    }//GEN-LAST:event_ButtonCEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculadora20.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculadora20.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculadora20.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculadora20.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                calculadora20 calculadora = new calculadora20();
                calculadora.setLocationRelativeTo(null);
                calculadora.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCE;
    private javax.swing.JButton clearOperators;
    private javax.swing.JButton divisor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton multiplicacao;
    private javax.swing.JLabel operator1;
    private javax.swing.JLabel operator2;
    private javax.swing.JLabel result;
    private javax.swing.JButton soma;
    private javax.swing.JButton subtracao;
    private javax.swing.JLabel txtTitulo;
    private javax.swing.JTextField valor1;
    private javax.swing.JTextField valor2;
    // End of variables declaration//GEN-END:variables
}
